### PR TITLE
Added a few of our own packages

### PR DESCRIPTION
**Pull request by abjerner**
I hope it's okay to add ones own packages ;)

I can also see that most of the referenced packages link to the package page at Our Umbraco. Our packages tend to have more information available on the GitHub project page, so I've linked to them instead.

### CODE REVIEW

**Comment by leekelleher** [comment]
Thanks @abjerner - I think the other PRs that I've merged in have caused a conflict. If you could rebase your fork, I'll merge this in.

**Comment by leekelleher** [comment]
@abjerner ooooo, so it turns out that I can resolve the merge-conflict myself via the GitHub UI, _interesting!_ 🎉

**Comment by leekelleher** [comment]
@abjerner - if you could link to the Our Umbraco package pages, that'd be appreciated.
(Unless there's a reason the package can't be on Our Umbraco?) Thanks.

**Comment by abjerner** [comment]
@leekelleher I've updated the link to Our Umbraco instead. Let me know if I need to do anything further ;)

**Comment by leekelleher** [comment]
Awesome, thanks @abjerner!

**Pull request merged**
