### PR TITLE
Add Form Editor to the list

### PR DESCRIPTION
**Pull request by kjac**
Added [Form Editor](https://github.com/kjac/FormEditor) to the list of backoffice extensions.

### CODE REVIEW

**Comment by leekelleher** [comment]
Awesome, thanks @kjac! 🎉

**Comment by leekelleher** [comment]
@kjac - sorry, I didn't notice it was a link to your GitHub repo.  Is Form Editor available on Our Umbraco?

**Comment by kjac** [comment]
@leekelleher nope... as per the [terms for Our Umbraco](https://our.umbraco.org/terms-and-conditions), it's not allowed: 

> "...don’t promote products on our.umbraco.org that directly compete with our commercial offerings which enables us to work for a sustainable Umbraco."

So GitHub releases it is.

**Comment by leekelleher** [comment]
Thanks @kjac - kudos to you for respecting their terms.

I'll give some thought about updating the [CONTRIBUTING guidelines](https://github.com/leekelleher/awesome-umbraco/blob/master/CONTRIBUTING.md) to cover these types of scenarios.

**Comment by kjac** [comment]
@leekelleher don't put too much work into it... I doubt it's a common scenario, specially since a lot of the other "offending" packages don't really respect the terms 😆

**Pull request merged**
